services:
  db:
    image: 'postgres:14'
    container_name: 'postgres-container'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_DB=authorization_service'

  app:
    image: backend-1
    container_name: 'first-instance-container'
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres-container:5432/authorization_service"
      spring.jpa.hibernate.ddl.auto: "none"

  instance:
    image: backend-2
    container_name: 'second-instance-container'
    ports:
      - 8081:8080
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres-container:5432/authorization_service"
      spring.jpa.hibernate.ddl.auto: "none"