spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization_service
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
